<?php

namespace UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Request;

class UserController extends Controller
{
    /**
     * User profile.
     *
     * @Route("/profile", name="sf_user_profile")
     * @Method({"GET", "POST"})
     */
    public function profileAction(Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_USER', null, 'Unable to access this page!');

        $user = $this->getUser();
        $logo = $user->getLogo();
        $form = $this->createForm('UserBundle\Form\UserMyProfileType', $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           $logo_new = $user->getLogo();
            if($logo_new == null){
                $user->setLogo($logo);
            }else{
                $fileName = md5(uniqid()).'.'.$logo_new->guessExtension();
                $logo_new->move(
                    $this->getParameter('logos_directory') . '/' . $user->getId(),
                    $fileName
                );
                $user->setLogo($fileName);

            }

            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('sf_user_profile');
        }

        return $this->render('UserBundle:User:profile.html.twig', array(
            'user' => $user,
            'form' => $form->createView(),
            'title' => 'Mon profil',
            'header' => 'Archi<span>space</span>'
        ));
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
