<?php

namespace AdministrationBundle\Repository;

/**
 * chartdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chartdataRepository extends \Doctrine\ORM\EntityRepository
{
}
