<?php

namespace AdministrationBundle\Repository;

/**
 * seekersBibRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seekersBibRepository extends \Doctrine\ORM\EntityRepository
{

}
