<?php

namespace AdministrationBundle\Repository;

/**
 * statRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statRepository extends \Doctrine\ORM\EntityRepository
{
}
